# Generated by Django 2.2.4 on 2019-08-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=5)),
                ('periodo', models.CharField(max_length=10)),
                ('valor', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Escalas',
            },
        ),
    ]
